<script src="{{asset('js/jquery-3.4.1.js')}}"></script>
<!-- <script src="{{asset('js/jquery.min.js')}}"></script> -->
<script src="{{asset('js/jquery.countTo.js')}}"></script>
<script src="{{asset('js/jquery.fancybox.min.js')}}"></script>
<script src="{{asset('js/jquery.zoom.min.js')}}"></script>
<script src="{{asset('js/aos.js')}}"></script>
<script src="{{asset('js/all.js')}}"></script>
<script src="{{asset('js/uikit.min.js')}}"></script>
<script src="{{asset('js/uikit-icons.min.js')}}"></script>
<script src="{{asset('js/app.js')}}"></script>
